### ISSUE TITLE
Support config via prettier

### ISSUE THREAD

**Issue by kekel87** [ggascoigne/prettier-plugin-import-sort#11]
I do not find that the configuration should be in the `package.json`. Would it be possible to support the configuration files [prettier](https://prettier.io/docs/en/configuration.html) (`.prettierrc`, ...)?

**Comment by ggascoigne** [comment]
The issue here is that the config for import-sort lives where that plugin chooses, that means that it will read them from `package.json` or from `.importsortrc`.  This is unlikely to be changed as part of this package, but you could request this over at https://github.com/renke/import-sort if you like.
